export const FAKE_TV_SHOWS = {
  results: [
    {
      adult: false,
      backdrop_path: "/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
      genre_ids: [35, 10767],
      id: 59941,
      origin_country: ["US"],
      original_language: "en",
      original_name: "The Tonight Show Starring Jimmy Fallon",
      overview:
        "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
      popularity: 3025.581,
      poster_path: "/g4amxJvtpnY79J77xeamnAEUO8r.jpg",
      first_air_date: "2014-02-17",
      name: "The Tonight Show Starring Jimmy Fallon",
      vote_average: 5.867,
      vote_count: 297,
    },
  ],
};

export const FAKE_RECOMMENDATIONS = {
  results: [
    {
      adult: false,
      backdrop_path: "/amtOltTVcK9vQtL1iQS6p3LBi05.jpg",
      id: 62223,
      name: "The Late Late Show with James Corden",
      original_language: "en",
      original_name: "The Late Late Show with James Corden",
      overview:
        "Once Craig Ferguson retires, James Corden will be taking over The Late Late Show. The show is a late night talk show that interviews celebrities and has its own bits. And of course, it's all hosted by James Corden.",
      poster_path: "/qPmVoG8G9tc1nN8ZwGV2zYcknit.jpg",
      media_type: "tv",
      genre_ids: [10767],
      popularity: 1289.483,
      first_air_date: "2015-03-23",
      vote_average: 5.496,
      vote_count: 120,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/uganUhifpqzzAunI0PETnutlmR.jpg",
      id: 8621,
      name: "Late Night with Jimmy Fallon",
      original_language: "en",
      original_name: "Late Night with Jimmy Fallon",
      overview:
        "Late Night with Jimmy Fallon is an American late-night talk show airing weeknights at 12:35 am Eastern/11:35 pm Central on NBC in the United States. The hour-long show premiered on March 2, 2009, and is hosted by actor, comedian and performer Jimmy Fallon, an alumnus of Saturday Night Live. Hip hop/neo soul band The Roots serve as the show's house band, and Steve Higgins is the show's announcer.\n\nThe third incarnation of the Late Night franchise originated by David Letterman, the program originates from NBC Studio 6B in the GE Building at 30 Rockefeller Center in New York City. The show typically opens with a brief monologue from Fallon, followed by a comedy \"desk piece,\" as well as prerecorded segments and audience competitions. The next segment is devoted to a celebrity interview, with guests ranging from actors and musicians to media personalities and political figures. The show then closes with either a musical or comedy performance. The show frequently employs digital media into its comedy, which has become crucial to its success. Fallon has been appointed to become the next host of The Tonight Show, where he will succeed the current host Jay Leno at the conclusion of the 2014 Winter Olympics, with fellow SNL alum Seth Meyers slated to replace Fallon.",
      poster_path: "/l8WzbOr7vg3WDlB3hoy32wZDxwj.jpg",
      media_type: "tv",
      genre_ids: [10767],
      popularity: 286.28,
      first_air_date: "2009-03-02",
      vote_average: 5.9,
      vote_count: 85,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg",
      id: 1399,
      name: "Game of Thrones",
      original_language: "en",
      original_name: "Game of Thrones",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
      media_type: "tv",
      genre_ids: [10765, 18, 10759],
      popularity: 815.538,
      first_air_date: "2011-04-17",
      vote_average: 8.4,
      vote_count: 22833,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg",
      id: 63770,
      name: "The Late Show with Stephen Colbert",
      original_language: "en",
      original_name: "The Late Show with Stephen Colbert",
      overview:
        "Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.",
      poster_path: "/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg",
      media_type: "tv",
      genre_ids: [35, 10767],
      popularity: 2020.306,
      first_air_date: "2015-09-08",
      vote_average: 6.5,
      vote_count: 247,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/4s0F03DpjFkKOAihuAqKtRLJCsC.jpg",
      id: 37678,
      name: "The Voice",
      original_language: "en",
      original_name: "The Voice",
      overview:
        "The strongest vocalists from across the United states compete in a blockbusters vocal competition, the winner becomes “The Voice.” The show's innovative format features four stages of competition: the blind auditions, the battle rounds, the knockouts and, finally, the live performance shows.",
      poster_path: "/sjtly63wIdTEgdtGvCAOB9AeEyg.jpg",
      media_type: "tv",
      genre_ids: [10764],
      popularity: 375.412,
      first_air_date: "2011-04-26",
      vote_average: 5.977,
      vote_count: 193,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/w0GA9tmKfRgxXj2zPUp0qzDuYjC.jpg",
      id: 60694,
      name: "Last Week Tonight with John Oliver",
      original_language: "en",
      original_name: "Last Week Tonight with John Oliver",
      overview:
        "A half-hour satirical look at the week in news, politics and current events.",
      poster_path: "/b12eM3FXNjN7yM7XYTIdmeQRud9.jpg",
      media_type: "tv",
      genre_ids: [10767, 35, 10763],
      popularity: 387.661,
      first_air_date: "2014-04-27",
      vote_average: 7.882,
      vote_count: 626,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/9OYKpQvBwGovPCAoi4AWAADxTau.jpg",
      id: 1489,
      name: "Jimmy Kimmel Live!",
      original_language: "en",
      original_name: "Jimmy Kimmel Live!",
      overview:
        "Jimmy Kimmel Live! is an American late-night talk show, created and hosted by Jimmy Kimmel and broadcast on ABC.",
      poster_path: "/6uKEYejjR88GwHgNq6NAQ30glTx.jpg",
      media_type: "tv",
      genre_ids: [10767, 35],
      popularity: 664.215,
      first_air_date: "2003-01-26",
      vote_average: 5.475,
      vote_count: 141,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/dfX2UaHVE5c7kLBFbgmEZJuy4Ev.jpg",
      id: 61818,
      name: "Late Night with Seth Meyers",
      original_language: "en",
      original_name: "Late Night with Seth Meyers",
      overview:
        'Seth Meyers, who is "Saturday Night Live’s" longest serving anchor on the show’s wildly popular "Weekend Update," takes over as host of NBC’s "Late Night" — home to A-list celebrity guests, memorable comedy and the best in musical talent. As the Emmy Award-winning head writer for "SNL," Meyers has established a reputation for sharp wit and perfectly timed comedy, and has gained fame for his spot-on jokes and satire. Meyers takes his departure from "SNL" to his new post at "Late Night," as Jimmy Fallon moves to "The Tonight Show".',
      poster_path: "/gZlu4cTS1XS9FtZjC0hX7eRE0Sv.jpg",
      media_type: "tv",
      genre_ids: [10767, 35],
      popularity: 744.191,
      first_air_date: "2014-02-25",
      vote_average: 5.6,
      vote_count: 77,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
      id: 76479,
      name: "The Boys",
      original_language: "en",
      original_name: "The Boys",
      overview:
        "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
      poster_path: "/7Ns6tO3aYjppI5bFhyYZurOYGBT.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759],
      popularity: 408.465,
      first_air_date: "2019-07-25",
      vote_average: 8.472,
      vote_count: 9253,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/x4salpjB11umlUOltfNvSSrjSXm.jpg",
      id: 1402,
      name: "The Walking Dead",
      original_language: "en",
      original_name: "The Walking Dead",
      overview:
        "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
      poster_path: "/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg",
      media_type: "tv",
      genre_ids: [10759, 18, 10765],
      popularity: 588.212,
      first_air_date: "2010-10-31",
      vote_average: 8.119,
      vote_count: 15903,
      origin_country: ["US"],
    },
  ],
};
